title: "CMPS290S, Fall 2018"
description: "Languages and Abstractions for Distributed Programming"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "default", "dark", "dirt", "neon", "mint", "plum", "sunrise"

paginate: 5 # number of posts to show
paginate_path: /page:num/

repository: "lkuper/CMPS290S-2018-09"

baseurl: "/CMPS290S-2018-09"

exclude: responses

plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
